<?php

namespace App\DataFixtures;

use App\Entity\Matiere;



use Doctrine\Bundle\FixturesBundle\Fixture;
use Doctrine\Persistence\ObjectManager;

class MatieresRefFixtures extends Fixture
{
	public function load(ObjectManager $manager): void
	{

		$matieres =[["matiere"=>"Abaca", "matiere_en"=>""], 
			["matiere"=>"Acétate", "matiere_en"=>""], 
			["matiere"=>"Acétate (doublure)", "matiere_en"=>""], 
			["matiere"=>"Acétate (empiècement)", "matiere_en"=>""], 
			["matiere"=>"Acier", "matiere_en"=>""], 
			["matiere"=>"Acier inoxydable ", "matiere_en"=>""], 
			["matiere"=>"Acrylique", "matiere_en"=>""], 
			["matiere"=>"Acrylique (doublure)", "matiere_en"=>""], 
			["matiere"=>"Acrylique (rembourrage)", "matiere_en"=>""], 
			["matiere"=>"Alashan cashmere", "matiere_en"=>""], 
			["matiere"=>"Alcantara", "matiere_en"=>""], 
			["matiere"=>"Alpaga", "matiere_en"=>""], 
			["matiere"=>"Alpaga (doublure)", "matiere_en"=>""], 
			["matiere"=>"Aluminium", "matiere_en"=>""], 
			["matiere"=>"Angora", "matiere_en"=>""], 
			["matiere"=>"Angora (doublure)", "matiere_en"=>""], 
			["matiere"=>"Angora de lapin", "matiere_en"=>""], 
			["matiere"=>"Ardoise", "matiere_en"=>""], 
			["matiere"=>"Argent", "matiere_en"=>""], 
			["matiere"=>"Argent sterling", "matiere_en"=>""], 
			["matiere"=>"Astrakan", "matiere_en"=>""], 
			["matiere"=>"Autres fibres", "matiere_en"=>""], 
			["matiere"=>"Baby cashmere", "matiere_en"=>""], 
			["matiere"=>"Bambou", "matiere_en"=>""], 
			["matiere"=>"Bois", "matiere_en"=>""], 
			["matiere"=>"Bois de rose", "matiere_en"=>""], 
			["matiere"=>"Branchage", "matiere_en"=>""], 
			["matiere"=>"Bronze", "matiere_en"=>""], 
			["matiere"=>"Cachemire", "matiere_en"=>""], 
			["matiere"=>"Cachemire (doublure)", "matiere_en"=>""], 
			["matiere"=>"Calcédoine", "matiere_en"=>""], 
			["matiere"=>"Cannetille (empiècement)", "matiere_en"=>""], 
			["matiere"=>"Caoutchouc", "matiere_en"=>""], 
			["matiere"=>"Carbone", "matiere_en"=>""], 
			["matiere"=>"Carcasse", "matiere_en"=>""], 
			["matiere"=>"Carton", "matiere_en"=>""], 
			["matiere"=>"Céramique", "matiere_en"=>""], 
			["matiere"=>"Chanvre", "matiere_en"=>""], 
			["matiere"=>"Chrome", "matiere_en"=>""], 
			["matiere"=>"Cire", "matiere_en"=>""], 
			["matiere"=>"Cire végétale", "matiere_en"=>""], 
			["matiere"=>"Cordon métallique", "matiere_en"=>""], 
			["matiere"=>"Cordovan", "matiere_en"=>""], 
			["matiere"=>"Corne", "matiere_en"=>""], 
			["matiere"=>"Coton", "matiere_en"=>""], 
			["matiere"=>"Coton (doublure)", "matiere_en"=>""], 
			["matiere"=>"Coton (empiècement)", "matiere_en"=>""], 
			["matiere"=>"Cristal", "matiere_en"=>""], 
			["matiere"=>"Cristaux", "matiere_en"=>""], 
			["matiere"=>"Cristaux de sel de mer", "matiere_en"=>""], 
			["matiere"=>"Cristaux Swarovski", "matiere_en"=>""], 
			["matiere"=>"Cuir", "matiere_en"=>""], 
			["matiere"=>"Cuir (doublure)", "matiere_en"=>""], 
			["matiere"=>"Cuir (semelles)", "matiere_en"=>""], 
			["matiere"=>"Cuir d'agneau", "matiere_en"=>""], 
			["matiere"=>"Cuir d'agneau (doublure)", "matiere_en"=>""], 
			["matiere"=>"Cuir d'âne", "matiere_en"=>""], 
			["matiere"=>"Cuir d'antilope", "matiere_en"=>""], 
			["matiere"=>"Cuir d'autruche", "matiere_en"=>""], 
			["matiere"=>"Cuir de bélier", "matiere_en"=>""], 
			["matiere"=>"Cuir de bison", "matiere_en"=>""], 
			["matiere"=>"Cuir de boeuf", "matiere_en"=>""], 
			["matiere"=>"Cuir de buffle", "matiere_en"=>""], 
			["matiere"=>"Cuir de buffle d'eau", "matiere_en"=>""], 
			["matiere"=>"Cuir de cerf", "matiere_en"=>""], 
			["matiere"=>"Cuir de chameau", "matiere_en"=>""], 
			["matiere"=>"Cuir de cheval", "matiere_en"=>""], 
			["matiere"=>"Cuir de cheval (doublure)", "matiere_en"=>""], 
			["matiere"=>"Cuir de chèvre", "matiere_en"=>""], 
			["matiere"=>"Cuir de chèvre (doublure)", "matiere_en"=>""], 
			["matiere"=>"Cuir de chevreau", "matiere_en"=>""], 
			["matiere"=>"Cuir de crocodile", "matiere_en"=>""], 
			["matiere"=>"Cuir de kangourou", "matiere_en"=>""], 
			["matiere"=>"Cuir de karung", "matiere_en"=>""], 
			["matiere"=>"Cuir de mouton (doublure)", "matiere_en"=>""], 
			["matiere"=>"Cuir de requin", "matiere_en"=>""], 
			["matiere"=>"Cuir de serpent", "matiere_en"=>""], 
			["matiere"=>"Cuir de taureau", "matiere_en"=>""], 
			["matiere"=>"Cuir de vache", "matiere_en"=>""], 
			["matiere"=>"Cuir de vachette", "matiere_en"=>""], 
			["matiere"=>"Cuir de veau", "matiere_en"=>""], 
			["matiere"=>"Cuir de veau (doublure)", "matiere_en"=>""], 
			["matiere"=>"Cuir de veau (semelles)", "matiere_en"=>""], 
			["matiere"=>"Cuir de veau sans chrome", "matiere_en"=>""], 
			["matiere"=>"Cuir de yack", "matiere_en"=>""], 
			["matiere"=>"Cuir nappa", "matiere_en"=>""], 
			["matiere"=>"Cuir synthétique", "matiere_en"=>""], 
			["matiere"=>"Cuivre", "matiere_en"=>""], 
			["matiere"=>"Cupro", "matiere_en"=>""], 
			["matiere"=>"Cupro (doublure)", "matiere_en"=>""], 
			["matiere"=>"Cupro (empiècement)", "matiere_en"=>""], 
			["matiere"=>"Daim", "matiere_en"=>""], 
			["matiere"=>"Diamants", "matiere_en"=>""], 
			["matiere"=>"Diamants falamank", "matiere_en"=>""], 
			["matiere"=>"Diamants Icy", "matiere_en"=>""], 
			["matiere"=>"Diamants noirs", "matiere_en"=>""], 
			["matiere"=>"Duvet (rembourrage)", "matiere_en"=>""], 
			["matiere"=>"Duvet d'oie (rembourrage)", "matiere_en"=>""], 
			["matiere"=>"Duvet de canard (rembourrage)", "matiere_en"=>""], 
			["matiere"=>"Élasthanne", "matiere_en"=>""], 
			["matiere"=>"Élasthanne (doublure)", "matiere_en"=>""], 
			["matiere"=>"Élastique", "matiere_en"=>""], 
			["matiere"=>"Elastodiène", "matiere_en"=>""], 
			["matiere"=>"Élastomère", "matiere_en"=>""], 
			["matiere"=>"Elastomultiester", "matiere_en"=>""], 
			["matiere"=>"Elite", "matiere_en"=>""], 
			["matiere"=>"Elite (doublure)", "matiere_en"=>""], 
			["matiere"=>"Émaille", "matiere_en"=>""], 
			["matiere"=>"Encens", "matiere_en"=>""], 
			["matiere"=>"Étain", "matiere_en"=>""], 
			["matiere"=>"EVA (semelles)", "matiere_en"=>""], 
			["matiere"=>"Fausse fourrure", "matiere_en"=>""], 
			["matiere"=>"Fer", "matiere_en"=>""], 
			["matiere"=>"Feutre de castor", "matiere_en"=>""], 
			["matiere"=>"Feutre de lapin", "matiere_en"=>""], 
			["matiere"=>"Fibre", "matiere_en"=>""], 
			["matiere"=>"Fibre de verre", "matiere_en"=>""], 
			["matiere"=>"Fibre métallique", "matiere_en"=>""], 
			["matiere"=>"Fil d'acier", "matiere_en"=>""], 
			["matiere"=>"Fil de cuivre", "matiere_en"=>""], 
			["matiere"=>"Fil métallique", "matiere_en"=>""], 
			["matiere"=>"Flax", "matiere_en"=>""], 
			["matiere"=>"Fluorofibre", "matiere_en"=>""], 
			["matiere"=>"Fourrure", "matiere_en"=>""], 
			["matiere"=>"Fourrure d'agneau", "matiere_en"=>""], 
			["matiere"=>"Fourrure d'agneau (doublure)", "matiere_en"=>""], 
			["matiere"=>"Fourrure d'orylag", "matiere_en"=>""], 
			["matiere"=>"Fourrure de castor", "matiere_en"=>""], 
			["matiere"=>"Fourrure de chèvre", "matiere_en"=>""], 
			["matiere"=>"Fourrure de coyote", "matiere_en"=>""], 
			["matiere"=>"Fourrure de kalgan", "matiere_en"=>""], 
			["matiere"=>"Fourrure de kidassia", "matiere_en"=>""], 
			["matiere"=>"Fourrure de lapin", "matiere_en"=>""], 
			["matiere"=>"Fourrure de lapin (doublure)", "matiere_en"=>""], 
			["matiere"=>"Fourrure de mouton", "matiere_en"=>""], 
			["matiere"=>"Laine cachemire", "matiere_en"=>""], 
			["matiere"=>"Plastique", "matiere_en"=>""], 
			["matiere"=>"Plexiglas", "matiere_en"=>""], 
			["matiere"=>"Fourrure de poney", "matiere_en"=>""], 
			["matiere"=>"Fourrure de ragondin", "matiere_en"=>""], 
			["matiere"=>"Fourrure de raton laveur", "matiere_en"=>""], 
			["matiere"=>"Fourrure de renard", "matiere_en"=>""], 
			["matiere"=>"Fourrure de renard doré", "matiere_en"=>""], 
			["matiere"=>"Fourrure de rex", "matiere_en"=>""], 
			["matiere"=>"Fourrure de swakara", "matiere_en"=>""], 
			["matiere"=>"Fourrure de vison", "matiere_en"=>""], 
			["matiere"=>"Fujiflex", "matiere_en"=>""], 
			["matiere"=>"Glycérine", "matiere_en"=>""], 
			["matiere"=>"Gomme (semelles)", "matiere_en"=>""], 
			["matiere"=>"Grenat", "matiere_en"=>""], 
			["matiere"=>"Grès", "matiere_en"=>""], 
			["matiere"=>"Grille métallique", "matiere_en"=>""], 
			["matiere"=>"Gypse", "matiere_en"=>""], 
			["matiere"=>"Hématite", "matiere_en"=>""], 
			["matiere"=>"Huile", "matiere_en"=>""], 
			["matiere"=>"Huile de silicone", "matiere_en"=>""], 
			["matiere"=>"Ikat", "matiere_en"=>""], 
			["matiere"=>"Inox", "matiere_en"=>""], 
			["matiere"=>"Jeune alpaga", "matiere_en"=>""], 
			["matiere"=>"Jeune alpaga royal", "matiere_en"=>""], 
			["matiere"=>"Jute", "matiere_en"=>""], 
			["matiere"=>"Kid Mohair", "matiere_en"=>""], 
			["matiere"=>"Laine", "matiere_en"=>""], 
			["matiere"=>"Laine d'agneau", "matiere_en"=>""], 
			["matiere"=>"Laine d'alpaga", "matiere_en"=>""], 
			["matiere"=>"Laine de chameau", "matiere_en"=>""], 
			["matiere"=>"Laine (doublure)", "matiere_en"=>""], 
			["matiere"=>"Laine (empiècement)", "matiere_en"=>""], 
			["matiere"=>"Laine mérinos", "matiere_en"=>""], 
			["matiere"=>"Laine polaire", "matiere_en"=>""], 
			["matiere"=>"Laine shetland", "matiere_en"=>""], 
			["matiere"=>"Laine vierge", "matiere_en"=>""], 
			["matiere"=>"Laine vierge", "matiere_en"=>""], 
			["matiere"=>"Laine vierge (doublure)", "matiere_en"=>""], 
			["matiere"=>"Laine de yack", "matiere_en"=>""], 
			["matiere"=>"Laiton", "matiere_en"=>""], 
			["matiere"=>"Laiton argenté", "matiere_en"=>""], 
			["matiere"=>"Laiton plaqué or", "matiere_en"=>""], 
			["matiere"=>"Lama", "matiere_en"=>""], 
			["matiere"=>"Lapin", "matiere_en"=>""], 
			["matiere"=>"Liège", "matiere_en"=>""], 
			["matiere"=>"Lin", "matiere_en"=>""], 
			["matiere"=>"Lin (doublure)", "matiere_en"=>""], 
			["matiere"=>"Lolite", "matiere_en"=>""], 
			["matiere"=>"Lucite", "matiere_en"=>""], 
			["matiere"=>"Lurex métallique", "matiere_en"=>""], 
			["matiere"=>"Lycra", "matiere_en"=>""], 
			["matiere"=>"Lycra (doublure)", "matiere_en"=>""], 
			["matiere"=>"Lyocell", "matiere_en"=>""], 
			["matiere"=>"Maille", "matiere_en"=>""], 
			["matiere"=>"Marbre", "matiere_en"=>""], 
			["matiere"=>"Marcassite", "matiere_en"=>""], 
			["matiere"=>"Mercure", "matiere_en"=>""], 
			["matiere"=>"Métal", "matiere_en"=>""], 
			["matiere"=>"Micro cellulaire (semelles)", "matiere_en"=>""], 
			["matiere"=>"Micro (semelles)", "matiere_en"=>""], 
			["matiere"=>"Micromodal", "matiere_en"=>""], 
			["matiere"=>"Modacrylique (doublure)", "matiere_en"=>""], 
			["matiere"=>"Modacrylique", "matiere_en"=>""], 
			["matiere"=>"Modal", "matiere_en"=>""], 
			["matiere"=>"Modal (doublure)", "matiere_en"=>""], 
			["matiere"=>"Mohair", "matiere_en"=>""], 
			["matiere"=>"Mohair (empiècement)", "matiere_en"=>""], 
			["matiere"=>"Mousse", "matiere_en"=>""], 
			["matiere"=>"Mouton", "matiere_en"=>""], 
			["matiere"=>"Mouton (doublure)", "matiere_en"=>""], 
			["matiere"=>"Nacre", "matiere_en"=>""], 
			["matiere"=>"Néoprène", "matiere_en"=>""], 
			["matiere"=>"Nickel", "matiere_en"=>""], 
			["matiere"=>"Nylon", "matiere_en"=>""], 
			["matiere"=>"Nylon (doublure)", "matiere_en"=>""], 
			["matiere"=>"Nylon (empiècement)", "matiere_en"=>""], 
			["matiere"=>"Onyx", "matiere_en"=>""], 
			["matiere"=>"Opossum", "matiere_en"=>""], 
			["matiere"=>"Or", "matiere_en"=>""], 
			["matiere"=>"Or blanc", "matiere_en"=>""], 
			["matiere"=>"Or rose", "matiere_en"=>""], 
			["matiere"=>"Paille", "matiere_en"=>""], 
			["matiere"=>"Paille de sisal", "matiere_en"=>""], 
			["matiere"=>"Palladium", "matiere_en"=>""], 
			["matiere"=>"Papier", "matiere_en"=>""], 
			["matiere"=>"Papier japonais", "matiere_en"=>""], 
			["matiere"=>"Patine de bronze", "matiere_en"=>""], 
			["matiere"=>"Plastique recyclé (APET)", "matiere_en"=>""], 
			["matiere"=>"Peau d'agneau", "matiere_en"=>""], 
			["matiere"=>"Peau de cerf", "matiere_en"=>""], 
			["matiere"=>"Peau de chèvre", "matiere_en"=>""], 
			["matiere"=>"Peau de chèvre (doublure)", "matiere_en"=>""], 
			["matiere"=>"Peau de chamois", "matiere_en"=>""], 
			["matiere"=>"Peau de lapin", "matiere_en"=>""], 
			["matiere"=>"Peau de lézard", "matiere_en"=>""], 
			["matiere"=>"Peau de mouton", "matiere_en"=>""], 
			["matiere"=>"Peau retournée (agneau)", "matiere_en"=>""], 
			["matiere"=>"Peau retournée (mouton)", "matiere_en"=>""], 
			["matiere"=>"Peau de serpent", "matiere_en"=>""], 
			["matiere"=>"Peau de vache", "matiere_en"=>""], 
			["matiere"=>"Peau de vache (doublure)", "matiere_en"=>""], 
			["matiere"=>"Peau de veau", "matiere_en"=>""], 
			["matiere"=>"Peau de veau (doublure)", "matiere_en"=>""], 
			["matiere"=>"Perles", "matiere_en"=>""], 
			["matiere"=>"Perles de verre", "matiere_en"=>""], 
			["matiere"=>"Phylon (semelles)", "matiere_en"=>""], 
			["matiere"=>"Pierre", "matiere_en"=>""], 
			["matiere"=>"Pierre de lave", "matiere_en"=>""], 
			["matiere"=>"Plaqué or et laiton doré", "matiere_en"=>""], 
			["matiere"=>"Plastique (perles)", "matiere_en"=>""], 
			["matiere"=>"Platine", "matiere_en"=>""], 
			["matiere"=>"Galuchat", "matiere_en"=>""], 
			["matiere"=>"Plumes de canard (rembourrage)", "matiere_en"=>""], 
			["matiere"=>"Plumes", "matiere_en"=>""], 
			["matiere"=>"Plumes de dindon", "matiere_en"=>""], 
			["matiere"=>"Plumes d'oie (rembourrage)", "matiere_en"=>""], 
			["matiere"=>"Plumes de pintade", "matiere_en"=>""], 
			["matiere"=>"Plumes (rembourrage)", "matiere_en"=>""], 
			["matiere"=>"Poil de chameau (rembourrage)", "matiere_en"=>""], 
			["matiere"=>"Polyacrylique", "matiere_en"=>""], 
			["matiere"=>"Polyamide", "matiere_en"=>""], 
			["matiere"=>"Polyamide (empiècement)", "matiere_en"=>""], 
			["matiere"=>"Polyamide (doublure)", "matiere_en"=>""], 
			["matiere"=>"Polycarbonate", "matiere_en"=>""], 
			["matiere"=>"Polychlorure de vinyle", "matiere_en"=>""], 
			["matiere"=>"Polyester", "matiere_en"=>""], 
			["matiere"=>"Polyester (doublure)", "matiere_en"=>""], 
			["matiere"=>"Polyester (empiècement)", "matiere_en"=>""], 
			["matiere"=>"Polyester (rembourrage)", "matiere_en"=>""], 
			["matiere"=>"Polyéthylène", "matiere_en"=>""], 
			["matiere"=>"Polyéthylène (doublure)", "matiere_en"=>""], 
			["matiere"=>"Polyéthylène (rembourrage)", "matiere_en"=>""], 
			["matiere"=>"Polymetal", "matiere_en"=>""], 
			["matiere"=>"Polypropylène", "matiere_en"=>""], 
			["matiere"=>"Polystyrène", "matiere_en"=>""], 
			["matiere"=>"Polyuréthane", "matiere_en"=>""], 
			["matiere"=>"Polyuréthane (doublure)", "matiere_en"=>""], 
			["matiere"=>"Polyurethane thermoplastique", "matiere_en"=>""], 
			["matiere"=>"Porcelaine", "matiere_en"=>""], 
			["matiere"=>"Poudre de bronze", "matiere_en"=>""], 
			["matiere"=>"Poulain", "matiere_en"=>""], 
			["matiere"=>"Prasiolite", "matiere_en"=>""], 
			["matiere"=>"PVC", "matiere_en"=>""], 
			["matiere"=>"Pyrite", "matiere_en"=>""], 
			["matiere"=>"Python", "matiere_en"=>""], 
			["matiere"=>"Quartz", "matiere_en"=>""], 
			["matiere"=>"Quartz fumé", "matiere_en"=>""], 
			["matiere"=>"Ramie", "matiere_en"=>""], 
			["matiere"=>"Ramie (doublure)", "matiere_en"=>""], 
			["matiere"=>"Raphia", "matiere_en"=>""], 
			["matiere"=>"Rat musqué", "matiere_en"=>""], 
			["matiere"=>"Raton Laveur", "matiere_en"=>""], 
			["matiere"=>"Rayonne", "matiere_en"=>""], 
			["matiere"=>"Rayonne (doublure)", "matiere_en"=>""], 
			["matiere"=>"Renard", "matiere_en"=>""], 
			["matiere"=>"Renard argenté", "matiere_en"=>""], 
			["matiere"=>"Renard roux", "matiere_en"=>""], 
			["matiere"=>"Résine", "matiere_en"=>""], 
			["matiere"=>"Résine de nylon", "matiere_en"=>""], 
			["matiere"=>"Résine polyuréthane", "matiere_en"=>""], 
			["matiere"=>"Rhodochrosite", "matiere_en"=>""], 
			["matiere"=>"Roche", "matiere_en"=>""], 
			["matiere"=>"Roseau", "matiere_en"=>""], 
			["matiere"=>"Rotin", "matiere_en"=>""], 
			["matiere"=>"Ruban à gros grain", "matiere_en"=>""], 
			["matiere"=>"Rubis", "matiere_en"=>""], 
			["matiere"=>"Saphir", "matiere_en"=>""], 
			["matiere"=>"Satin", "matiere_en"=>""], 
			["matiere"=>"Serpent ayers", "matiere_en"=>""], 
			["matiere"=>"Shearling", "matiere_en"=>""], 
			["matiere"=>"Silicone", "matiere_en"=>""], 
			["matiere"=>"Silicone (semelles)", "matiere_en"=>""], 
			["matiere"=>"Soie", "matiere_en"=>""], 
			["matiere"=>"Silk (empiècement)", "matiere_en"=>""], 
			["matiere"=>"Soie de mûrier", "matiere_en"=>""], 
			["matiere"=>"Soie (doublure)", "matiere_en"=>""], 
			["matiere"=>"Soie grège", "matiere_en"=>""], 
			["matiere"=>"Spandex", "matiere_en"=>""], 
			["matiere"=>"Spandex (doublure)", "matiere_en"=>""], 
			["matiere"=>"Spandex/Élasthanne", "matiere_en"=>""], 
			["matiere"=>"Strass", "matiere_en"=>""], 
			["matiere"=>"Taffetas acétate (doublure)", "matiere_en"=>""], 
			["matiere"=>"Technique mixe", "matiere_en"=>""], 
			["matiere"=>"Teck", "matiere_en"=>""], 
			["matiere"=>"Tencel", "matiere_en"=>""], 
			["matiere"=>"Terre cuite", "matiere_en"=>""], 
			["matiere"=>"TEX/SYN", "matiere_en"=>""], 
			["matiere"=>"Tissu", "matiere_en"=>""], 
			["matiere"=>"Tissu", "matiere_en"=>""], 
			["matiere"=>"Tissu (doublure)", "matiere_en"=>""], 
			["matiere"=>"Tissu synthétique", "matiere_en"=>""], 
			["matiere"=>"Titane", "matiere_en"=>""], 
			["matiere"=>"Toile", "matiere_en"=>""], 
			["matiere"=>"Topaze", "matiere_en"=>""], 
			["matiere"=>"TPU", "matiere_en"=>""], 
			["matiere"=>"Triacétate", "matiere_en"=>""], 
			["matiere"=>"Veau pleine fleur (garniture)", "matiere_en"=>""], 
			["matiere"=>"Veau velours", "matiere_en"=>""], 
			["matiere"=>"Velours", "matiere_en"=>""], 
			["matiere"=>"Ventile", "matiere_en"=>""], 
			["matiere"=>"Verre", "matiere_en"=>""], 
			["matiere"=>"Verre recyclé", "matiere_en"=>""], 
			["matiere"=>"Viscose", "matiere_en"=>""], 
			["matiere"=>"Viscose (doublure)", "matiere_en"=>""], 
			["matiere"=>"Vison", "matiere_en"=>""], 
			["matiere"=>"Mink (doublure)", "matiere_en"=>""], 
			["matiere"=>"Vitrail", "matiere_en"=>""], 
			["matiere"=>"Washi", "matiere_en"=>""], 
			["matiere"=>"Zinc", "matiere_en"=>""], 
			["matiere"=>"Polytétrafluoroéthylène", "matiere_en"=>""], 
			["matiere"=>"Coton Organique", "matiere_en"=>""], 
			["matiere"=>"Polyuréthane Bio", "matiere_en"=>""], 
			["matiere"=>"Vacelites", "matiere_en"=>""], 
			["matiere"=>"Ethyléne-acétate de vinyle", "matiere_en"=>""], 
			["matiere"=>"Fibre de carbone", "matiere_en"=>""], 
			["matiere"=>"Cuir de mouton", "matiere_en"=>""], 
			["matiere"=>"Soie Tussah", "matiere_en"=>""], 
			["matiere"=>"polyvinyle", "matiere_en"=>""], 
			["matiere"=>"Plumes d'autruche", "matiere_en"=>""], 
			["matiere"=>"Cuir de veau (accessoires)", "matiere_en"=>""], 
			["matiere"=>"Plumes de Faisans", "matiere_en"=>""], 
			["matiere"=>"Chanvre (doublure)", "matiere_en"=>""], 
			["matiere"=>"Agneau (garniture)", "matiere_en"=>""], 
			["matiere"=>"acrylique (empiècement)", "matiere_en"=>""], 
			["matiere"=>"Cuir verni", "matiere_en"=>""], 
			["matiere"=>"Caoutchouc (semelle)", "matiere_en"=>""], 
			["matiere"=>"Laine mohair", "matiere_en"=>""], 
			["matiere"=>"polyester métalisé", "matiere_en"=>""], 
			["matiere"=>"Polyamide (bordure)", "matiere_en"=>""], 
			["matiere"=>"Viscose (bordure)", "matiere_en"=>""], 
			["matiere"=>"Rayonne (empiècement)", "matiere_en"=>""], 
			["matiere"=>"Tencel (empiècement)", "matiere_en"=>""], 
			["matiere"=>"Soie (empiècements)", "matiere_en"=>""], 
			["matiere"=>"Viscose (empiècement)", "matiere_en"=>""], 
			["matiere"=>"Magnésium", "matiere_en"=>""], 
			["matiere"=>"Sucre", "matiere_en"=>""], 
			["matiere"=>"Eau de Chevreuse", "matiere_en"=>""], 
			["matiere"=>"Lotus", "matiere_en"=>""], 
			["matiere"=>"Nepeta", "matiere_en"=>""], 
			["matiere"=>"Coquelicot", "matiere_en"=>""], 
			["matiere"=>"Mélisse", "matiere_en"=>""], 
			["matiere"=>"Jus de Citron", "matiere_en"=>""], 
			["matiere"=>"Glycérine végétale", "matiere_en"=>""], 
			["matiere"=>"CBD 500mg", "matiere_en"=>""], 
			["matiere"=>"Huile d’Olive de Tanche ", "matiere_en"=>""], 
			["matiere"=>"CBD", "matiere_en"=>""], 
			["matiere"=>"CBD 100mg", "matiere_en"=>""], 
			["matiere"=>"Miel", "matiere_en"=>""], 
			["matiere"=>"Propylène glycol (PG)", "matiere_en"=>""], 
			["matiere"=>"Glycérine végétale (VG", "matiere_en"=>""], 
			["matiere"=>"CBD (cannabidiol)", "matiere_en"=>""], 
			["matiere"=>"Terpènes", "matiere_en"=>""], 
			["matiere"=>"Mangue", "matiere_en"=>""], 
			["matiere"=>"Passion", "matiere_en"=>""], 
			["matiere"=>"Vanille", "matiere_en"=>""], 
			["matiere"=>"Sucre de canne", "matiere_en"=>""], 
			["matiere"=>"Citron", "matiere_en"=>""], 
			["matiere"=>"Pectine d’agrumes", "matiere_en"=>""], 
			["matiere"=>"Miel d’acacia français", "matiere_en"=>""], 
			["matiere"=>"Miel de fleurs français", "matiere_en"=>""], 
			["matiere"=>"Riz soufflé", "matiere_en"=>""], 
			["matiere"=>"Orange", "matiere_en"=>""], 
			["matiere"=>"Poivre rouge de kampot", "matiere_en"=>""], 
			["matiere"=>"Cuir de vache (empiècement)", "matiere_en"=>""], 
			["matiere"=>"Polyester recyclé", "matiere_en"=>""], 

			];


		sort($matieres);

		foreach ($matieres as $key => $value) {
			// code...
			$value["matiere"] = trim($value["matiere"]);
			$value["matiere_en"] = trim($value["matiere_en"]);
			
			$matieres = new Matiere($value);
			$find = $manager->getRepository(Matiere::class)->findOneBy([
				"matiere" => $matieres->getMatiere(),
			]);


            if(!$find){
                $manager->persist($matieres);
                $manager->flush();                
            }
		}
	}
}




