<?php

namespace App\DataFixtures;

use App\Entity\Pays;



use Doctrine\Bundle\FixturesBundle\Fixture;
use Doctrine\Persistence\ObjectManager;

class PaysFixtures extends Fixture
{
	public function load(ObjectManager $manager): void
	{

		$pays =[["pays"=>"Afghanistan", "continent"=>""], 
			["pays"=>"Afrique du sud", "continent"=>""], 
			["pays"=>"Albanie", "continent"=>""], 
			["pays"=>"Algérie", "continent"=>""], 
			["pays"=>"Allemagne", "continent"=>""], 
			["pays"=>"Angola", "continent"=>""], 
			["pays"=>"Anguilla", "continent"=>""], 
			["pays"=>"Antarctique", "continent"=>""], 
			["pays"=>"Antigua et Barbuda", "continent"=>""], 
			["pays"=>"Antilles Néerlandaises", "continent"=>""], 
			["pays"=>"Arabie Saoudite", "continent"=>""], 
			["pays"=>"Argentine", "continent"=>""], 
			["pays"=>"Arménie", "continent"=>""], 
			["pays"=>"Aruba", "continent"=>""], 
			["pays"=>"Australie", "continent"=>""], 
			["pays"=>"Autriche", "continent"=>""], 
			["pays"=>"Azerbaïdjan", "continent"=>""], 
			["pays"=>"Bahamas", "continent"=>""], 
			["pays"=>"Bahreïn", "continent"=>""], 
			["pays"=>"Bangladesh", "continent"=>""], 
			["pays"=>"Barbade", "continent"=>""], 
			["pays"=>"Belgique", "continent"=>""], 
			["pays"=>"Bengladesh", "continent"=>""], 
			["pays"=>"Bénin", "continent"=>""], 
			["pays"=>"Bermudes", "continent"=>""], 
			["pays"=>"Bhoutan", "continent"=>""], 
			["pays"=>"Biélorussie", "continent"=>""], 
			["pays"=>"Birmanie", "continent"=>""], 
			["pays"=>"Bolivie", "continent"=>""], 
			["pays"=>"Bonaire, Saint-Eustache et Saba", "continent"=>""], 
			["pays"=>"Bosnie-Herzégovine", "continent"=>""], 
			["pays"=>"Botswana", "continent"=>""], 
			["pays"=>"Brésil", "continent"=>""], 
			["pays"=>"Brunéi Darussalam", "continent"=>""], 
			["pays"=>"Bulgarie", "continent"=>""], 
			["pays"=>"Burkina Faso", "continent"=>""], 
			["pays"=>"Burundi", "continent"=>""], 
			["pays"=>"Cachemire", "continent"=>""], 
			["pays"=>"Cambodge", "continent"=>""], 
			["pays"=>"Cameroun", "continent"=>""], 
			["pays"=>"Canada", "continent"=>""], 
			["pays"=>"Cap-Vert", "continent"=>""], 
			["pays"=>"Chili", "continent"=>""], 
			["pays"=>"Chine", "continent"=>""], 
			["pays"=>"Chypre", "continent"=>""], 
			["pays"=>"Colombie", "continent"=>""], 
			["pays"=>"Comores", "continent"=>""], 
			["pays"=>"Congo", "continent"=>""], 
			["pays"=>"Corée du Sud", "continent"=>""], 
			["pays"=>"Corée du Sud", "continent"=>""], 
			["pays"=>"Costa Rica", "continent"=>""], 
			["pays"=>"Côte d'Ivoire", "continent"=>""], 
			["pays"=>"Croatie", "continent"=>""], 
			["pays"=>"Cuba", "continent"=>""], 
			["pays"=>"Curaçao", "continent"=>""], 
			["pays"=>"Danemark", "continent"=>""], 
			["pays"=>"Djibouti", "continent"=>""], 
			["pays"=>"Dominique", "continent"=>""], 
			["pays"=>"Ecosse", "continent"=>""], 
			["pays"=>"Égypte", "continent"=>""], 
			["pays"=>"Émirats Arabes Unis", "continent"=>""], 
			["pays"=>"Équateur", "continent"=>""], 
			["pays"=>"Érythrée", "continent"=>""], 
			["pays"=>"Espagne", "continent"=>""], 
			["pays"=>"Estonie", "continent"=>""], 
			["pays"=>"Ethiopie", "continent"=>""], 
			["pays"=>"EU", "continent"=>""], 
			["pays"=>"Fédération de Russie", "continent"=>""], 
			["pays"=>"Finlande", "continent"=>""], 
			["pays"=>"France", "continent"=>""], 
			["pays"=>"Gabon", "continent"=>""], 
			["pays"=>"Gambie", "continent"=>""], 
			["pays"=>"Georgie", "continent"=>""], 
			["pays"=>"Géorgie du Sud-et-les Îles Sandwich du Sud", "continent"=>""], 
			["pays"=>"Ghana", "continent"=>""], 
			["pays"=>"Gibraltar", "continent"=>""], 
			["pays"=>"Grèce", "continent"=>""], 
			["pays"=>"Grenade", "continent"=>""], 
			["pays"=>"Groënland", "continent"=>""], 
			["pays"=>"Guadeloupe", "continent"=>""], 
			["pays"=>"Guam (É-U)", "continent"=>""], 
			["pays"=>"Guatemala", "continent"=>""], 
			["pays"=>"Guernesey", "continent"=>""], 
			["pays"=>"Guinée", "continent"=>""], 
			["pays"=>"Guinée Bissau", "continent"=>""], 
			["pays"=>"Guinée Équatoriale", "continent"=>""], 
			["pays"=>"Guyane", "continent"=>""], 
			["pays"=>"Guyane Française", "continent"=>""], 
			["pays"=>"Haïti", "continent"=>""], 
			["pays"=>"Honduras", "continent"=>""], 
			["pays"=>"Hong-Kong", "continent"=>""], 
			["pays"=>"Hongrie", "continent"=>""], 
			["pays"=>"Île Bouvet", "continent"=>""], 
			["pays"=>"Île Christmas", "continent"=>""], 
			["pays"=>"Île de Man", "continent"=>""], 
			["pays"=>"Île Maurice", "continent"=>""], 
			["pays"=>"Île Norfolk", "continent"=>""], 
			["pays"=>"Îles Caïmans", "continent"=>""], 
			["pays"=>"Îles Cocos (Keeling)", "continent"=>""], 
			["pays"=>"Îles Cook", "continent"=>""], 
			["pays"=>"Îles Féroé", "continent"=>""], 
			["pays"=>"Îles Fidji", "continent"=>""], 
			["pays"=>"Îles Heard et McDonald", "continent"=>""], 
			["pays"=>"Îles Malouines", "continent"=>""], 
			["pays"=>"Îles Mariannes du Nord", "continent"=>""], 
			["pays"=>"Îles Marshall", "continent"=>""], 
			["pays"=>"Îles mineures éloignées des États-Unis", "continent"=>""], 
			["pays"=>"Îles Pitcairn", "continent"=>""], 
			["pays"=>"Îles Salomon", "continent"=>""], 
			["pays"=>"Îles Turques et Caïques", "continent"=>""], 
			["pays"=>"Îles Vierges (Britaniques)", "continent"=>""], 
			["pays"=>"Îles Vierges (USA)", "continent"=>""], 
			["pays"=>"Inde", "continent"=>""], 
			["pays"=>"Indonésie", "continent"=>""], 
			["pays"=>"Irak", "continent"=>""], 
			["pays"=>"Iran", "continent"=>""], 
			["pays"=>"Irlande", "continent"=>""], 
			["pays"=>"Islande", "continent"=>""], 
			["pays"=>"Israël", "continent"=>""], 
			["pays"=>"Italie", "continent"=>""], 
			["pays"=>"Jamaïque", "continent"=>""], 
			["pays"=>"Japon", "continent"=>""], 
			["pays"=>"Jordanie", "continent"=>""], 
			["pays"=>"Kazakhstan", "continent"=>""], 
			["pays"=>"Kenya", "continent"=>""], 
			["pays"=>"Kiribati", "continent"=>""], 
			["pays"=>"Koweït", "continent"=>""], 
			["pays"=>"Laos", "continent"=>""], 
			["pays"=>"Le Belize", "continent"=>""], 
			["pays"=>"Lesotho", "continent"=>""], 
			["pays"=>"Lettonie", "continent"=>""], 
			["pays"=>"Liban", "continent"=>""], 
			["pays"=>"Liberia", "continent"=>""], 
			["pays"=>"Libye", "continent"=>""], 
			["pays"=>"Liechtenstein", "continent"=>""], 
			["pays"=>"Lituanie", "continent"=>""], 
			["pays"=>"Londres", "continent"=>""], 
			["pays"=>"Luxembourg", "continent"=>""], 
			["pays"=>"Macao", "continent"=>""], 
			["pays"=>"Macédoine", "continent"=>""], 
			["pays"=>"Madagascar", "continent"=>""], 
			["pays"=>"Malaisie", "continent"=>""], 
			["pays"=>"Malawi", "continent"=>""], 
			["pays"=>"Maldives", "continent"=>""], 
			["pays"=>"Mali", "continent"=>""], 
			["pays"=>"Malte", "continent"=>""], 
			["pays"=>"Maroc", "continent"=>""], 
			["pays"=>"Martinique (Française)", "continent"=>""], 
			["pays"=>"Mauritanie", "continent"=>""], 
			["pays"=>"Mayotte", "continent"=>""], 
			["pays"=>"Mexique", "continent"=>""], 
			["pays"=>"Micronésie", "continent"=>""], 
			["pays"=>"Moldavie", "continent"=>""], 
			["pays"=>"Monaco", "continent"=>""], 
			["pays"=>"Mongolie", "continent"=>""], 
			["pays"=>"Monténégro", "continent"=>""], 
			["pays"=>"Montserrat", "continent"=>""], 
			["pays"=>"Mozambique", "continent"=>""], 
			["pays"=>"Namibie", "continent"=>""], 
			["pays"=>"Nauru", "continent"=>""], 
			["pays"=>"Népal", "continent"=>""], 
			["pays"=>"Nicaragua", "continent"=>""], 
			["pays"=>"Niger", "continent"=>""], 
			["pays"=>"Nigéria", "continent"=>""], 
			["pays"=>"Niué", "continent"=>""], 
			["pays"=>"Norvège", "continent"=>""], 
			["pays"=>"Nouvelle Calédonie (Française)", "continent"=>""], 
			["pays"=>"Nouvelle-Zélande", "continent"=>""], 
			["pays"=>"Oman", "continent"=>""], 
			["pays"=>"Ouganda", "continent"=>""], 
			["pays"=>"Ouzbékistan", "continent"=>""], 
			["pays"=>"Pakistan", "continent"=>""], 
			["pays"=>"Palau", "continent"=>""], 
			["pays"=>"Panama", "continent"=>""], 
			["pays"=>"Papouasie-Nouvelle-Guinée", "continent"=>""], 
			["pays"=>"Paraguay", "continent"=>""], 
			["pays"=>"Pays-Bas", "continent"=>""], 
			["pays"=>"Pérou", "continent"=>""], 
			["pays"=>"Philippines", "continent"=>""], 
			["pays"=>"Pologne", "continent"=>""], 
			["pays"=>"Polynésie (Française)", "continent"=>""], 
			["pays"=>"Porto Rico", "continent"=>""], 
			["pays"=>"Portugal", "continent"=>""], 
			["pays"=>"Principauté d'Andorre", "continent"=>""], 
			["pays"=>"Qatar", "continent"=>""], 
			["pays"=>"République Centre-Africaine", "continent"=>""], 
			["pays"=>"République démocratique du Congo", "continent"=>""], 
			["pays"=>"République Dominicaine", "continent"=>""], 
			["pays"=>"République Kirghize (Kirghizistan)", "continent"=>""], 
			["pays"=>"République tchèque", "continent"=>""], 
			["pays"=>"Réunion (Française)", "continent"=>""], 
			["pays"=>"Roumanie", "continent"=>""], 
			["pays"=>"Royaume-Uni", "continent"=>""], 
			["pays"=>"Rwanda", "continent"=>""], 
			["pays"=>"Sahara Occidental", "continent"=>""], 
			["pays"=>"Saint Barthélémy", "continent"=>""], 
			["pays"=>"Saint Christophe et Niévès", "continent"=>""], 
			["pays"=>"Saint Pierre et Miquelon", "continent"=>""], 
			["pays"=>"Saint Vincent & Grenadines", "continent"=>""], 
			["pays"=>"Saint-Martin (partie française)", "continent"=>""], 
			["pays"=>"Saint-Martin (partie néerlandaise)", "continent"=>""], 
			["pays"=>"Saint-Siège (État du Vatican)", "continent"=>""], 
			["pays"=>"Sainte Hélène", "continent"=>""], 
			["pays"=>"Sainte-Lucie", "continent"=>""], 
			["pays"=>"Salvador", "continent"=>""], 
			["pays"=>"Samoa", "continent"=>""], 
			["pays"=>"Samoa américaines", "continent"=>""], 
			["pays"=>"San-Marin", "continent"=>""], 
			["pays"=>"Sao Tomé et Principe", "continent"=>""], 
			["pays"=>"Sénégal", "continent"=>""], 
			["pays"=>"Serbie", "continent"=>""], 
			["pays"=>"Seychelles", "continent"=>""], 
			["pays"=>"Sierra Leone", "continent"=>""], 
			["pays"=>"Singapour", "continent"=>""], 
			["pays"=>"Slovaquie", "continent"=>""], 
			["pays"=>"Slovénie", "continent"=>""], 
			["pays"=>"Somalie", "continent"=>""], 
			["pays"=>"Soudan", "continent"=>""], 
			["pays"=>"Sri Lanka", "continent"=>""], 
			["pays"=>"Sud Soudan", "continent"=>""], 
			["pays"=>"Suède", "continent"=>""], 
			["pays"=>"Suisse", "continent"=>""], 
			["pays"=>"Suriname", "continent"=>""], 
			["pays"=>"Svalbard et îles Jan Mayen", "continent"=>""], 
			["pays"=>"Swaziland", "continent"=>""], 
			["pays"=>"Syrie", "continent"=>""], 
			["pays"=>"Tadjikistan", "continent"=>""], 
			["pays"=>"Taïwan", "continent"=>""], 
			["pays"=>"Tanzanie", "continent"=>""], 
			["pays"=>"Tchad", "continent"=>""], 
			["pays"=>"Terres Australes Françaises", "continent"=>""], 
			["pays"=>"Territoire britannique de l'océan Indien", "continent"=>""], 
			["pays"=>"Territoire palestinien, occupé", "continent"=>""], 
			["pays"=>"Thaïlande", "continent"=>""], 
			["pays"=>"Timor Oriental", "continent"=>""], 
			["pays"=>"Togo", "continent"=>""], 
			["pays"=>"Tokelau", "continent"=>""], 
			["pays"=>"Tonga", "continent"=>""], 
			["pays"=>"Trinité et Tobago", "continent"=>""], 
			["pays"=>"Tunisie", "continent"=>""], 
			["pays"=>"Turkménistan", "continent"=>""], 
			["pays"=>"Turquie", "continent"=>""], 
			["pays"=>"Tuvalu", "continent"=>""], 
			["pays"=>"Ukraine", "continent"=>""], 
			["pays"=>"Uruguay", "continent"=>""], 
			["pays"=>"USA", "continent"=>""], 
			["pays"=>"Vanuatu", "continent"=>""], 
			["pays"=>"Venezuela", "continent"=>""], 
			["pays"=>"Vietnam", "continent"=>""], 
			["pays"=>"Wallis et Futuna", "continent"=>""], 
			["pays"=>"Yémen", "continent"=>""], 
			["pays"=>"Yougoslavie", "continent"=>""], 
			["pays"=>"Zaïre", "continent"=>""], 
			["pays"=>"Zambie", "continent"=>""], 
			["pays"=>"Zimbabwe", "continent"=>""], 
			["pays"=>"Zone neutre", "continent"=>""], 

			];
		sort($pays);

		foreach ($pays as $key => $value) {
			// code...
			$value["pays"] = trim($value["pays"]);
			$value["continent"] = trim($value["continent"]);	

			$pays = new Pays($value);
			$find = $manager->getRepository(Pays::class)->findOneBy([
				"pays" => $pays->getPays(),
			]);


            if(!$find){
                $manager->persist($pays);
                $manager->flush();                
            }
		}
	}
}




